// <auto-generated />
namespace CMR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FacultyAssignmentRemoveUnusedField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FacultyAssignmentRemoveUnusedField));
        
        string IMigrationMetadata.Id
        {
            get { return "201603220735165_FacultyAssignmentRemoveUnusedField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
